/*
 * The catch keyword catches exceptions generated by try statements.
	The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.
	we can also use multiple catch statements to handle multiple exceptions for a single try but the exception should be correct
		
 */
public class TryCatch {
	public static void main(String args[]) {
		int num1=100;
		int num2=50;
		int num;
		try {
		num=num1/0;
		}catch(ArithmeticException e) {
			System.out.println(e);
		}
		catch(ArrayIndexOutOfBoundsException e) {
			System.out.println(e);
		}
		System.out.println("rest of the code runs as usally");
		System.out.println(num1*num2);
		
			
		
	}

}
